### ISSUE TITLE
Cannot open the main panel

### ISSUE THREAD

**Issue by RobinPang** [nik9play/tinyBrightness#6]
I can open the control panel via right click, but I cannot open the main panel via left click.

**Comment by nik9play** [comment]
Try clicking two times, some times it only works that way.

**Comment by nik9play** [comment]
If this doesn't work, please send the version of windows and tinyBrightness you use.

**Comment by RobinPang** [comment]
> If this doesn't work, please send the version of windows and tinyBrightness you use.

I have tried to click two times, and I also ran it on another laptop with two versions(1.5 and 1.4). It didn't work, too.
Surface Pro4 - Windows 10 Pro 1909 - 1.5 and 1.4
Asus ROG Strix Scar II - Windows 10 Pro 1909 - 1.5

**Comment by nik9play** [comment]
> Surface Pro4 - Windows 10 Pro 1909 - 1.5 and 1.4
ASUS ROG Strix Scar II - Windows 10 Pro 1909 - 1.5

I see... Laptops? I think there are problems on devices with built-in display. BTW it works on my laptop with Win7 but doesn't on Win10 tablet. However, tinyBrightness cannot change brightness of built-in display since tinyBrightness use DDC/CI. I'll try to fix issue with popup. Thanks for reporting

**Comment by nik9play** [comment]
I figured something out. The popup does not open on monitors with DPI scale > 100% due to wrong positioning. I'm working on fix.

**Comment by nik9play** [comment]
try v1.6
